sudo: required

services:
- docker

addons:
  apt:
    packages:
      - docker-ce

install: skip

jobs:
  include:
    - &deploy-stage
      stage: build and deploy
      script:
        # set up the base image
        - sed -i "s#^FROM .*#FROM ${DOCKER_FROM}#" Dockerfile
        # setup QEMU
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        # build
        - docker build -t $DOCKER_IMAGE:$DOCKER_TAG -f Dockerfile .
        # test
        #- docker run --rm $DOCKER_IMAGE:$DOCKER_TAG 'curl --version && jq --version'
      after_success:
        - |
          docker login -u="clabu" -p="${DOCKER_PASSWORD}"
          docker tag $DOCKER_IMAGE:$DOCKER_TAG clabu/$DOCKER_IMAGE:$DOCKER_TAG
          docker push clabu/$DOCKER_IMAGE:$DOCKER_TAG
      env:
        - DOCKER_TAG=armhf
        - DOCKER_FROM=rycus86/armhf-alpine-qemu

env:
  global:
  - DOCKER_IMAGE=utils
